name: GoldBigDragonRPG
main: GBD.GoldBigDragon_Advanced.Main.Main
version: 20151108
description: Mabinogi!!!
commands:
  돈:
    description: 자신의 소지 금액을 확인합니다.
  스텟:
    description: 캐릭터의 스텟을 확인합니다.
  옵션:
    description: 게임 옵션을 조절합니다.
  기타:
    description: 기타 기능들을 확인합니다.
  파티:
    description: 파티 관련 GUI창을 엽니다.
  오피박스:
    description: 서버 OP만의 설정 GUI창을 엽니다.
  아이템:
    description: 아이템 관련 명령어를 실행합니다.
  몬스터:
    description: 몬스터 관련 명령어를 실행합니다.
  워프:
    description: 워프 관련 명령어를 실행합니다.
  영역:
    description: 영역 관련 명령어를 실행합니다.
  상점:
    description: NPC의 상점 관련 명령어를 실행합니다.
  엔티티제거:
    description: /엔티티제거 [숫자]
  아이템제거:
    description: /아이템제거 [숫자]
  퀘스트:
    description: 퀘스트 관련 GUI창을 엽니다.
  커맨드:
    description: 스킬 커맨드 등록용 커맨드 입니다.
  스킬:
    description: 자신의 스킬 창을 확인합니다.
  친구:
    description: 친구 GUI창을 엽니다.
  gui사용:
    description: 비활성화 시킨 NPC의 GUI창을 활성화 시킵니다.
  테스트:
    description: 테스트용 명령어 입니다.